spring.application.name=student-management
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/student_management
spring.datasource.username=root
spring.datasource.password=Deepseem@11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Optional
spring.cache.type=redis


jwt.secret=8f4c1f2d9ab4e6f7c8d9a0b1c2d3e4f56a7b8c9d0e1f2a3b4c5d6e7f8